/* Local book reader: text extraction only; imported documents never leave this browser. */
window.Reader=(()=>{
  let active=null,chapter=0,opening=false;
  const fileTypes=['pdf','epub','txt','md','markdown','html','htm','docx','fb2','mobi','azw3','azw'];
  const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const extension=name=>String(name).split('.').pop().toLowerCase();
  const pause=()=>new Promise(resolve=>setTimeout(resolve,0));
  function ensure(s){s.readerBooks=Array.isArray(s.readerBooks)?s.readerBooks:[];s.readerLocations=s.readerLocations&&typeof s.readerLocations==='object'?s.readerLocations:{};s.readerResume=s.readerResume&&typeof s.readerResume==='object'?s.readerResume:{};return s;}
  function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open('shiji-reader-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('books');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
  async function saveFile(id,file){const db=await database();try{await new Promise((resolve,reject)=>{const tx=db.transaction('books','readwrite');tx.objectStore('books').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
  async function loadFile(id){const db=await database();try{return await new Promise((resolve,reject)=>{const request=db.transaction('books').objectStore('books').get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}finally{db.close();}}
  async function deleteFile(id){const db=await database();try{await new Promise((resolve,reject)=>{const tx=db.transaction('books','readwrite');tx.objectStore('books').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
  function paragraphs(text){return String(text||'').replace(/\r/g,'').split(/\n\s*\n|\n(?=.{0,80}\n)/).map(x=>x.replace(/\s*\n\s*/g,' ').trim()).filter(x=>x.length>1);}
  function chunks(rows,size=16){const out=[];for(let i=0;i<rows.length;i+=size)out.push(rows.slice(i,i+size));return out;}
  function fromDocument(doc){for(const el of doc.querySelectorAll('script,style,nav,footer,head'))el.remove();const nodes=[...doc.querySelectorAll('h1,h2,h3,h4,p,li,blockquote')].filter(el=>!el.querySelector('p,h1,h2,h3,h4,li,blockquote'));const rows=nodes.map(el=>el.textContent.replace(/\s+/g,' ').trim()).filter(x=>x.length>1);return rows.length?rows:paragraphs(doc.body?.textContent||doc.documentElement?.textContent||'');}
  async function parsePlain(file){const bytes=await file.arrayBuffer();let text=new TextDecoder('utf-8').decode(bytes);if((text.match(/�/g)||[]).length>10)text=new TextDecoder('gb18030').decode(bytes);const ext=extension(file.name);if(['html','htm'].includes(ext)){const doc=new DOMParser().parseFromString(text,'text/html');return chunks(fromDocument(doc)).map((rows,i)=>({title:`第 ${i+1} 段`,rows}));}return chunks(paragraphs(text)).map((rows,i)=>({title:`第 ${i+1} 段`,rows}));}
  async function parseDocx(file){const zip=await JSZip.loadAsync(file),entry=zip.file('word/document.xml');if(!entry)throw Error('DOCX 正文不存在。');const doc=new DOMParser().parseFromString(await entry.async('string'),'application/xml');const rows=[...doc.getElementsByTagName('w:p')].map(p=>[...p.getElementsByTagName('w:t')].map(n=>n.textContent).join('').trim()).filter(Boolean);return chunks(rows).map((rows,i)=>({title:`第 ${i+1} 段`,rows}));}
  function xmlElements(parent,name){return [...parent.getElementsByTagName('*')].filter(el=>el.localName===name);}
  function zipPath(base,href){const url=new URL(href,'https://book.local/'+base);return decodeURIComponent(url.pathname.slice(1));}
  async function parseEpub(file,status){const zip=await JSZip.loadAsync(file),container=zip.file('META-INF/container.xml');if(!container)throw Error('EPUB 目录不存在。');const root=new DOMParser().parseFromString(await container.async('string'),'application/xml');const opfPath=xmlElements(root,'rootfile')[0]?.getAttribute('full-path'),opfFile=zip.file(opfPath||'');if(!opfFile)throw Error('EPUB 正文目录不存在。');const opf=new DOMParser().parseFromString(await opfFile.async('string'),'application/xml');const manifest=new Map(xmlElements(opf,'item').map(x=>[x.getAttribute('id'),x.getAttribute('href')]));const spine=xmlElements(opf,'itemref').map(x=>x.getAttribute('idref'));const base=opfPath.includes('/')?opfPath.slice(0,opfPath.lastIndexOf('/')+1):'';const sections=[];for(let i=0;i<spine.length;i++){const href=manifest.get(spine[i]),entry=href&&zip.file(zipPath(base,href));if(!entry)continue;const doc=new DOMParser().parseFromString(await entry.async('string'),'application/xhtml+xml');const rows=fromDocument(doc);if(rows.length)sections.push({title:rows[0].slice(0,70)||`章节 ${i+1}`,rows});if(i%8===0){status(`正在读取章节 ${i+1} / ${spine.length}`);await pause();}}return sections;}
  async function parseFb2(file){const doc=new DOMParser().parseFromString(await file.text(),'application/xml');const body=xmlElements(doc,'body')[0];if(!body)throw Error('FB2 正文不存在。');const sections=xmlElements(body,'section').filter(x=>!x.parentElement?.closest('section'));const roots=sections.length?sections:[body];return roots.map((section,i)=>{const rows=xmlElements(section,'p').map(x=>x.textContent.trim()).filter(Boolean);return{title:rows[0]?.slice(0,70)||`章节 ${i+1}`,rows};}).filter(x=>x.rows.length);}
  async function parseMobi(file,status){const {MOBI}=await import(window.SHIJI_MOBI_MODULE_URL||'./vendor/mobi.mjs');const unzlib=async bytes=>new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer());const parser=new MOBI({unzlib});const book=await parser.open(file),sections=[];for(let i=0;i<book.sections.length;i++){const doc=await book.sections[i].createDocument();const rows=fromDocument(doc);if(rows.length)sections.push({title:rows[0].slice(0,70)||`章节 ${i+1}`,rows});if(i%5===0){status(`正在读取章节 ${i+1} / ${book.sections.length}`);await pause();}}book.destroy?.();return sections;}
  async function parsePdf(file,status){if(!window.pdfjsLib)throw Error('PDF 解析器未加载。');pdfjsLib.GlobalWorkerOptions.workerSrc=window.SHIJI_PDF_WORKER_URL||'vendor/pdf.worker.min.js';const task=pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}),pdf=await task.promise,sections=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent(),rows=[],line=[];for(const item of content.items){if(item.str)line.push(item.str);if(item.hasEOL&&line.length){rows.push(line.join(' ').trim());line.length=0;}}if(line.length)rows.push(line.join(' ').trim());sections.push({title:`第 ${n} 页`,rows:rows.filter(Boolean)});if(n%5===0||n===1){status(`正在读取第 ${n} / ${pdf.numPages} 页`);await pause();}}await pdf.destroy();return sections;}
  async function parse(file,status){const ext=extension(file.name);if(!fileTypes.includes(ext))throw Error('暂不支持此格式，请转换为 EPUB、PDF、TXT 或 DOCX。');if(file.size>80*1024*1024)throw Error('文件超过 80 MB，请先拆分或压缩。');let sections;if(ext==='pdf')sections=await parsePdf(file,status);else if(ext==='epub')sections=await parseEpub(file,status);else if(ext==='docx')sections=await parseDocx(file);else if(ext==='fb2')sections=await parseFb2(file);else if(['mobi','azw3','azw'].includes(ext))sections=await parseMobi(file,status);else sections=await parsePlain(file);if(!sections.length||!sections.some(x=>x.rows.length))throw Error(ext==='pdf'?'未提取到文字。这可能是扫描版 PDF，需要先做文字识别。':'文件里没有可阅读的文字。');return sections;}
  function tokenize(text){return String(text).split(/([A-Za-z]+(?:['’\-][A-Za-z]+)*)/g).map(part=>/^[A-Za-z]+(?:['’\-][A-Za-z]+)*$/.test(part)?`<span class="reader-word" data-reader-word="${escape(part)}" role="button" tabindex="0">${escape(part)}</span>`:escape(part)).join('');}
  function render(s){ensure(s);const current=active&&s.readerBooks.find(x=>x.id===active.id),page=current?active.sections[chapter]:null;return `<section class="intro"><div><div class="eyebrow">READ & LOOK UP</div><h1>读到哪，查到哪。</h1><p>点英文词看本地释义；划选词组，可到常用在线词典继续查用法。</p></div><span class="pill">仅在本机</span></section><section class="card reader-import"><div><span class="section-label">导入自己的书</span><h2>从一页开始读。</h2><p>支持 PDF、EPUB、TXT、DOCX、HTML、Markdown、FB2 及未加密的 MOBI/AZW3。只提取文字用于阅读，文件保存在这个浏览器中。</p></div><label class="btn reader-upload" for="reader-file">选择文件<input id="reader-file" type="file" accept=".pdf,.epub,.txt,.docx,.html,.htm,.md,.markdown,.fb2,.mobi,.azw3,.azw" hidden></label><p class="hint" id="reader-status">扫描版 PDF 暂无文字识别；受加密保护的电子书无法打开。</p></section><section class="reader-layout"><section class="card reader-library"><span class="section-label">我的书架</span><h2>${s.readerBooks.length} 本书</h2><form id="reader-search" class="reader-search"><input name="word" type="search" maxlength="100" placeholder="输入单词或词组" aria-label="查词内容" required><button type="submit">查词</button></form>${s.readerBooks.length?s.readerBooks.map(x=>`<div class="reader-book ${current?.id===x.id?'active':''}"><button type="button" data-open-book="${escape(x.id)}"><strong>${escape(x.name)}</strong><small>${escape(x.type.toUpperCase())} · 上次读到 ${Math.min(100,Math.round(((s.readerLocations[x.id]||0)+1)/(x.chapters||1)*100))}%</small></button><button type="button" data-remove-book="${escape(x.id)}" aria-label="从书架移除 ${escape(x.name)}">×</button></div>`).join(''):'<p class="hint">导入后，书会出现在这里。</p>'}</section><section class="card reader-page">${page?`<div class="reader-page-top"><span class="section-label">${escape(current.name)}</span><span>${chapter+1} / ${active.sections.length}</span></div><h2>${escape(page.title)}</h2><div id="reader-text" lang="en">${page.rows.map(row=>`<p>${tokenize(row)}</p>`).join('')||'<p class="hint">此页没有可提取的文字。</p>'}</div><div class="reader-controls"><button type="button" data-reader-prev ${chapter===0?'disabled':''}>← 上一页</button><span>${Math.round((chapter+1)/active.sections.length*100)}%</span><button type="button" data-reader-next ${chapter===active.sections.length-1?'disabled':''}>下一页 →</button></div>`:`<div class="reader-empty"><span class="section-label">阅读区</span><h2>选择一本书，开始阅读。</h2><p>阅读位置会自动保存。</p></div>`}<div id="reader-lookup" class="reader-lookup" aria-live="polite"><p>点击单词、划选词组，或在左侧输入内容查词。</p></div></section></section>`;}
  function showLookup(term,s,save){const el=document.querySelector('#reader-lookup');if(!el)return;const result=Dictionary.lookup(term,s.selectedBook),links=Dictionary.links(term);if(!result)return;el.innerHTML=`<div class="lookup-top"><strong lang="en">${escape(result.query)}</strong><span>${escape(result.book?Learning.labels[result.book]:'在线查词')}</span></div>${result.phonetic?`<p>${escape(result.phonetic)}</p>`:''}<p>${escape(result.meaning)}</p><div class="dictionary-links">${links.map(x=>`<a href="${x.url}" target="_blank" rel="noopener noreferrer">${x.label} ↗</a>`).join('')}</div><button class="text-button" type="button" id="reader-save-word">加入纠错本</button>`;el.scrollIntoView({block:'nearest',behavior:'smooth'});el.querySelector('#reader-save-word').onclick=()=>{Coach.addError(s,{id:`reader-${result.query.toLowerCase()}`,type:'word',title:result.query,wrong:'阅读时不熟悉',correct:result.book?result.meaning:'待从在线词典核对',source:`我的阅读 · ${active?.name||''}`});save();el.querySelector('#reader-save-word').textContent='✓ 已加入纠错本';};}
  function bind(s,save,rerender,toast){ensure(s);document.querySelector('#reader-search')?.addEventListener('submit',e=>{e.preventDefault();showLookup(new FormData(e.currentTarget).get('word'),s,save);});document.querySelector('#reader-file')?.addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file||opening)return;opening=true;const status=text=>{const el=document.querySelector('#reader-status');if(el)el.textContent=text;};try{status('正在读取文件…');const sections=await parse(file,status),id=crypto.randomUUID(),fingerprint=`${file.name}|${file.size}`;await saveFile(id,file);s.readerBooks.push({id,name:file.name,type:extension(file.name),chapters:sections.length,fingerprint});chapter=Math.min(sections.length-1,s.readerResume[fingerprint]||0);s.readerLocations[id]=chapter;active={id,name:file.name,sections};save();rerender();toast(`已导入 ${file.name}。`);}catch(error){status(error.message||'文件读取失败。');}finally{opening=false;event.target.value='';}});document.querySelectorAll('[data-open-book]').forEach(button=>button.onclick=async()=>{const id=button.dataset.openBook;if(active?.id===id){chapter=s.readerLocations[id]||0;rerender();return;}const status=text=>{const el=document.querySelector('#reader-status');if(el)el.textContent=text;};try{status('正在打开书籍…');const file=await loadFile(id);if(!file)throw Error('浏览器里找不到文件，请重新导入。');const sections=await parse(file,status);active={id,name:file.name,sections};chapter=Math.min(sections.length-1,s.readerLocations[id]||0);rerender();}catch(error){status(error.message||'打开失败。');}});document.querySelectorAll('[data-remove-book]').forEach(button=>button.onclick=async()=>{const id=button.dataset.removeBook;await deleteFile(id);s.readerBooks=s.readerBooks.filter(x=>x.id!==id);delete s.readerLocations[id];if(active?.id===id){active=null;chapter=0;}save();rerender();});const move=step=>{chapter=Math.max(0,Math.min(active.sections.length-1,chapter+step));s.readerLocations[active.id]=chapter;const info=s.readerBooks.find(x=>x.id===active.id);if(info?.fingerprint)s.readerResume[info.fingerprint]=chapter;save();rerender();};document.querySelector('[data-reader-prev]')?.addEventListener('click',()=>move(-1));document.querySelector('[data-reader-next]')?.addEventListener('click',()=>move(1));document.querySelectorAll('[data-reader-word]').forEach(el=>{el.onclick=()=>{if(window.getSelection()?.toString().trim())return;showLookup(el.dataset.readerWord,s,save);};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showLookup(el.dataset.readerWord,s,save);}};});document.querySelector('#reader-text')?.addEventListener('pointerup',()=>{const selection=window.getSelection(),term=selection?.toString().trim();if(term&&term.split(/\s+/).length>1&&term.length<=100)showLookup(term,s,save);});}
  return{ensure,render,bind};
})();
